POST http://localhost:3001/api/blogs/620a78fe1dea7f30e0af6d1c/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZhbkIiLCJpZCI6IjYxMWVhNjM0OTEzMzhjMDk0YzllZGEzMSIsImlhdCI6MTY0NDg1MzM5M30.O4jXlZdbTNe5zGcvvHVgz1o0min9wO03qj935m0I7wA

{
  "content": "test comment"
}